import type { CarrierCategory } from "./carrier";

export type CategoryGuide = { category: CarrierCategory; title: string; summary: string; distinctions: string[]; questions: string[]; boundaries: string[] };

export const categoryGuides: Record<CarrierCategory, CategoryGuide> = {
  water: { category: "water", title: "Water detection and automatic shutoff", summary: "Point alerts, whole-home flow monitoring, and automatic main-line shutoff solve different parts of the problem.", distinctions: ["Point sensor: detects water only where the sensor is placed.", "Whole-home monitoring: observes flow patterns across the supplied plumbing.", "Automatic shutoff: can close the main water line after a supported detection event."], questions: ["Is automatic main-line shutoff actually requested?", "Will the valve, pipe, power, Wi-Fi, and installation conditions work?", "What proof, if any, will the carrier accept?"], boundaries: ["Detection does not guarantee shutoff or damage prevention.", "Carrier treatment, installation acceptance, and documentation require direct confirmation."] },
  gas: { category: "gas", title: "Automatic gas shutoff capability", summary: "An automatic or seismic shutoff valve is not the same as a detector, manual wrench, or utility shutoff procedure.", distinctions: ["Automatic/seismic valve: interrupts gas flow under its listed trigger conditions.", "Gas detector: alerts; it does not close the service line.", "Manual tool: requires a person and is not automatic protection.", "Utility procedure: follows the serving utility's emergency direction."], questions: ["Which valve type and listing are accepted locally?", "Does the serving utility or building department require a permit, installer, inspection, or reconnection procedure?", "Has the carrier confirmed the exact capability and documentation?"], boundaries: ["Do not install, adjust, test, or reopen gas service as a DIY project.", "Local code, utility rules, property configuration, professional scope, and insurer acceptance remain unknown until confirmed."] },
  security: { category: "security", title: "Fire alarm and security monitoring", summary: "A local alarm, phone alert, professional monitoring service, outside signal, and dispatch connection are distinct capabilities.", distinctions: ["Local alert: sounds at the property.", "Remote app alert: notifies an account or phone.", "Professional monitoring: a service receives qualifying signals under its terms.", "Dispatch linkage: the provider may contact emergency services under its protocol; it is not created by an app notification.", "Sprinklers: a separate installed life-safety system, not a monitoring synonym."], questions: ["Is fire, burglary, or both being discussed?", "Is central/professional monitoring required, and is the provider documentation current?", "What are the subscription, connectivity, backup power, testing, and maintenance terms?"], boundaries: ["A phone notification alone does not establish discount eligibility.", "For an active emergency, leave danger and contact emergency services; do not rely on this guide."] },
  "connected-home": { category: "connected-home", title: "Connected-home monitoring and control", summary: "Remote monitoring/control can depend on hubs, clouds, accounts, subscriptions, integrations, power, and internet connectivity.", distinctions: ["Remote monitoring reports state away from the property.", "Remote control changes device state away from the property.", "Local control may continue during an internet outage; cloud-dependent features may not.", "Interoperability claims do not prove every feature works across ecosystems."], questions: ["Which ecosystem, radio, hub, account, and network are required?", "Which functions survive a cloud, provider, power, or internet outage?", "How are access, updates, retention, household consent, and account recovery handled?"], boundaries: ["Device capability is separate from carrier eligibility.", "No-subscription or local-control claims display only when current technical evidence supports them."] },
};

export function getCategoryGuide(category: CarrierCategory): CategoryGuide { return categoryGuides[category]; }
