import type { Metadata } from "next";
import Link from "next/link";
import { SiteFooter } from "@/app/components/SiteFooter";
import { SiteHeader } from "@/app/components/SiteHeader";
import { getDeviceById } from "@/app/lib/data";
import { getDeviceFits } from "@/app/lib/carrier";
export const metadata: Metadata = { title: "Compare Devices" };
type Props = { searchParams: Promise<{ items?: string; carrier?: string; jurisdiction?: string }> };
export default async function ComparePage({ searchParams }: Props) { const query = await searchParams; const ids = query.items?.split(",").slice(0,3) ?? []; const items = ids.map(getDeviceById).filter(Boolean); const carrierContext = query.carrier === "farmers" && query.jurisdiction === "CA"; return <><SiteHeader /><main className="page-main"><header className="page-hero"><p className="eyebrow">Side-by-side</p><h1>Compare what changes the decision.</h1><p>No composite score hides the tradeoffs. Cost, setup, subscription, connectivity, limits, and source freshness stay visible.</p></header>{items.length >= 2 ? <div className="comparison" style={{"--compare-count": items.length} as React.CSSProperties}>{items.map((device) => device ? <article key={device.id}><p className="eyebrow">{device.solution}</p><h2>{device.manufacturer}<span>{device.model}</span></h2><dl><div><dt>Best for</dt><dd>{device.bestFor}</dd></div><div><dt>Cost</dt><dd>{device.priceBand}</dd></div><div><dt>Setup</dt><dd>{device.installation}</dd></div><div><dt>Subscription</dt><dd>{device.subscription}</dd></div><div><dt>Connectivity</dt><dd>{device.connectivity}</dd></div><div><dt>Known limits</dt><dd><ul>{device.limitations.map((item)=><li key={item}>{item}</li>)}</ul></dd></div></dl>{carrierContext ? <div className="compare-insurance"><strong>Insurance relevance · separate evidence</strong>{getDeviceFits(device.id).length ? <p>{getDeviceFits(device.id)[0].fit === "explicitly-named-public-offer" ? "Current California Farmers public-offer record." : "Technical capability match; Farmers treatment requires confirmation."}</p> : <p>No current governed Farmers product overlay.</p>}</div> : null}<Link className="text-action" href={`/devices/${device.slug}`}>Full record</Link></article> : null)}</div> : <div className="empty-state"><h2>Choose at least two devices.</h2><p>The comparison link contains fewer than two current records.</p><Link className="button-primary" href="/devices">Choose devices</Link></div>}</main><SiteFooter /></> }
