"use client";
import Link from 'next/link';
import Image from 'next/image';
import { useCallback, useEffect, useRef, useState } from 'react';
import { taskKinds } from '@/app/lib/coveragefit-device';
import { protectionLabels, protectionStates, type ProtectionChecklist, type ProtectionId, type ProtectionState } from '@/app/lib/protection-bridge';
import './home-decision.css';
import './protection-checklist.css';
type Draft = { state: ProtectionState; consent: boolean };
async function api(value: Record<string,unknown>) { const response=await fetch('/api/coveragefit-device',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({bridgeVersion:2,...value}),cache:'no-store',credentials:'same-origin'});const result=await response.json();if(!response.ok)throw Error(result.error?.message||'The connection is unavailable. No update is confirmed.');return result; }
export function CoverageFitProtectionChecklist({returnOrigin}:{returnOrigin:string}) {
  const [data,setData]=useState<ProtectionChecklist|null>(null),[token,setToken]=useState(''),[active,setActive]=useState<ProtectionId>('water'),[drafts,setDrafts]=useState<Partial<Record<ProtectionId,Draft>>>({}),[busy,setBusy]=useState(false),[notice,setNotice]=useState('Opening your protection checklist…');
  const pending=useRef<Partial<Record<ProtectionId,{id:string;fingerprint:string}>>>({});
  const load=useCallback(async(key:string,keep?:ProtectionId)=>{setBusy(true);try{const result:ProtectionChecklist=await api({operation:'read',token:key});setData(result);setActive(keep&&result.tasks.some(t=>t.id===keep)?keep:result.activeTaskId);setDrafts({});pending.current={};setNotice('Your insurance decision and appointment stay in CoverageFit. Save an update below when you want your agent to know.');}catch(error){setData(null);setNotice(error instanceof Error?error.message:'Reopen your insurance review to continue.');}finally{setBusy(false);}},[]);
  useEffect(()=>{const key=new URLSearchParams(location.hash.slice(1)).get('h')||'';const frame=requestAnimationFrame(()=>{if(/^[A-Za-z0-9_-]{43}$/.test(key)){setToken(key);void load(key);}else setNotice('Open this checklist from the protection steps in your CoverageFit insurance review.');});return()=>cancelAnimationFrame(frame);},[load]);
  const task=data?.tasks.find(t=>t.id===active),recommendation=task?.recommendation,draft=task?(drafts[task.id]||{state:task.progress?.state||'agent-help',consent:false}):null;
  const burglary=data?.tasks.find(t=>t.id==='burglary')?.recommendation,fire=data?.tasks.find(t=>t.id==='fire')?.recommendation;
  function choose(state:ProtectionState){if(!task)return;setDrafts(old=>({...old,[task.id]:{state,consent:false}}));delete pending.current[task.id];}
  async function save(){if(!task||!draft?.consent||busy||!data)return;const id=task.id,update={taskId:id,state:draft.state,deviceId:draft.state==='considering'?recommendation?.id||'':'',expectedVersion:task.version,consent:true},fingerprint=JSON.stringify(update);if(pending.current[id]?.fingerprint!==fingerprint)pending.current[id]={id:crypto.randomUUID(),fingerprint};setBusy(true);setNotice(`Saving your ${protectionLabels[id].toLowerCase()} update…`);try{const result=await api({operation:'save',token,...update,requestId:pending.current[id]!.id});setData({...data,tasks:data.tasks.map(t=>t.id===id?{...t,version:result.version,progress:result.progress}:t)});setDrafts(old=>({...old,[id]:{state:draft.state,consent:false}}));delete pending.current[id];setNotice(`${protectionLabels[id]} update saved to your insurance review. Your agent can review it; insurer acceptance is still separate.`);}catch(error){setNotice(error instanceof Error?error.message:'No save is confirmed. Retry this update.');}finally{setBusy(false);}}
  return <section className="home-decision protection-checklist" aria-labelledby="protection-title">
    <header className="hd-heading"><div><p className="eyebrow">From your CoverageFit review</p><h1 id="protection-title">Your home protection next steps.</h1>{data?<p>{data.policy.carrier} · {data.policy.product}</p>:null}</div>{returnOrigin&&token?<a className="button-subtle" href={`${returnOrigin}/review/#deviceReturn=${token}`}>Return to my insurance review</a>:null}</header>
    <p className="hd-notice" role="status" aria-live="polite">{notice}</p>
    {data&&task&&draft?<>
      <ol className="protection-steps" aria-label="Protection steps selected by your agent">{data.tasks.map(t=><li key={t.id}><button disabled={busy} type="button" aria-pressed={active===t.id} onClick={()=>setActive(t.id)}><strong>{protectionLabels[t.id]}</strong><span>{t.progress?protectionStates[t.progress.state]:'Awaiting your update'}</span></button></li>)}</ol>
      {burglary&&fire&&burglary.provider===fire.provider?<p className="protection-shared">Your agent selected the same provider for burglary and fire. Ask for one coordinated quote covering both services, including any shared monitoring charge.</p>:null}
      <article className="protection-detail" aria-labelledby={`task-${task.id}`}>
        <div className="protection-detail-head"><p className="eyebrow">{taskKinds[task.kind]}</p>{task.dueDate?<p className="protection-due">Documented due date: <strong>{task.dueDate}</strong></p>:null}</div>
        <h2 id={`task-${task.id}`}>{protectionLabels[task.id]}</h2>
        <p className="protection-recommendation">{recommendation?.title||'Confirm the appropriate setup with your agent'}</p>
        {recommendation?<p>{recommendation.setup}</p>:null}
        {!task.current?<p className="protection-attention">This saved recommendation needs a current review. Ask your agent to confirm the next step; you can still report an existing system or request help.</p>:<div className="hd-primary-row">
          {task.id==='gas'?<a className="button-primary" href="https://www.cslb.ca.gov/onlineservices/dataportal/" target="_blank" rel="noopener noreferrer">Find a licensed installation professional</a>:<a className="button-primary" href={recommendation!.url} target="_blank" rel="noopener noreferrer">{task.id==='water'?'View the Farmers Moen offer':'View the recommended system'}</a>}
          {task.id==='gas'?<a className="hd-text-link" href={recommendation!.url} target="_blank" rel="noopener noreferrer">Little Firefighter valve information</a>:recommendation?.monitoringUrl?<a className="hd-text-link" href={recommendation.monitoringUrl} target="_blank" rel="noopener noreferrer">Professional monitoring details</a>:null}
        </div>}
        {task.id==='gas'?<p className="protection-help">Search by city/ZIP and appropriate license classification, then <a href="https://www.cslb.ca.gov/onlineservices/checklicenseII/checklicense.aspx" target="_blank" rel="noopener noreferrer">verify the contractor’s license</a>. Have the installer confirm scope, valve selection, permits and local requirements. A search result is not an endorsement or installation booking.</p>:null}
        {['burglary','fire'].includes(task.id)?<p className="protection-help">Arrange the compatible equipment and activate professional monitoring. Professional installation and professional monitoring are separate services. A camera, app notification or inactive subscription does not establish the recommended protection.</p>:null}
        <details className="protection-documentation"><summary>Costs and what to prepare for review</summary><p>{recommendation?.costNote||'Confirm equipment, installation and recurring charges with the provider.'}</p><p>{recommendation?.documentation||'Ask your agent which documentation is needed.'}</p><p>Arrange document delivery through the appropriate secure channel with your agent. No upload is available here.</p>{recommendation?<p>Setup record reviewed {recommendation.checkedAt} · next review due {recommendation.reviewDue}. Prices and availability must be confirmed directly.</p>:null}</details>
      </article>
      <section className="hd-next" aria-labelledby="protection-update"><h2 id="protection-update">What should your agent know?</h2><label className="hd-field">Your {protectionLabels[task.id].toLowerCase()} update<select disabled={busy||!task.canUpdate} value={draft.state} onChange={event=>choose(event.target.value as ProtectionState)}>{Object.entries(protectionStates).filter(([id])=>!id.startsWith('monitoring-')||['burglary','fire'].includes(task.id)).map(([id,label])=><option key={id} value={id} disabled={id==='considering'&&!task.current}>{label}</option>)}</select></label>
        {!task.canUpdate?<p className="protection-attention">The quote needs confirmation before this step can be updated. Return to your insurance review or contact your agent.</p>:null}
        <label className="hd-consent"><input disabled={busy||!task.canUpdate} type="checkbox" checked={draft.consent} onChange={event=>setDrafts(old=>({...old,[task.id]:{...draft,consent:event.target.checked}}))}/>Save this status and, if I’m considering it, the recommended setup to my linked CoverageFit review for my agent to see.</label>
        <div className="hd-primary-row"><button className="button-primary" disabled={busy||!task.canUpdate||!draft.consent||(draft.state==='considering'&&!task.current)} onClick={save}>{busy?'Saving…':'Save update to my insurance review'}</button><button className="button-subtle" disabled={busy} onClick={()=>load(token,active)}>Reload saved updates</button></div>
        <p className="protection-help">These are customer-reported updates. Reporting purchase, installation or active monitoring does not verify it or clear an insurance condition.</p>
      </section>
      <details className="protection-house"><summary>Explore these steps around a home</summary><figure className="hd-house"><div className="hd-house-image"><Image unoptimized src="/assets/home-protection-hero.png" alt="Illustrative cutaway home; the buttons identify protection topics, not assessed conditions" width={1664} height={936}/><div className="hd-markers">{data.tasks.map(t=><button type="button" key={t.id} disabled={busy} aria-label={`Show ${protectionLabels[t.id]}`} aria-pressed={active===t.id} className={active===t.id?'is-active':''} style={{left:({water:'67%',burglary:'29%',fire:'52%',gas:'83%'} as const)[t.id],top:({water:'70%',burglary:'58%',fire:'31%',gas:'72%'} as const)[t.id]}} onClick={()=>{setActive(t.id);document.getElementById('protection-title')?.scrollIntoView({behavior:'instant'});}}><span>{protectionLabels[t.id]}</span></button>)}</div></div><figcaption>Illustrative home · your property has not been assessed. Use the checklist above for every action.</figcaption></figure></details>
    </>:token?<button className="button-subtle" disabled={busy} onClick={()=>load(token)}>Retry connection</button>:null}
    <footer className="hd-footer"><Link href="/protect/home">Independent Home guidance</Link><p>SmartDevices is independent. These setups were selected by your agent. Equipment costs are separate from insurance; product selection does not establish carrier approval, a discount or bound coverage.</p></footer>
  </section>;
}
