"use client";
import Link from "next/link";
import Image from "next/image";
import { useCallback, useEffect, useRef, useState } from "react";
import type { Device } from "@/app/lib/data";
import { deviceTaskStates, taskKinds, type ConnectedTask, type DeviceTaskState } from "@/app/lib/coveragefit-device";
import "./home-decision.css";
async function connectedApi(value: Record<string, unknown>) {
  const response = await fetch("/api/coveragefit-device", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(value), cache: "no-store", credentials: "same-origin" });
  const result = await response.json(); if (!response.ok) throw new Error(result.error?.message || "Connection unavailable. Your insurance review is unchanged."); return result;
}
export function CoverageFitDeviceTask({ options, returnOrigin }: { options: Device[]; returnOrigin: string }) {
  const [task, setTask] = useState<ConnectedTask | null>(null), [token, setToken] = useState("");
  const [state, setState] = useState<DeviceTaskState>("agent-help"), [deviceId, setDeviceId] = useState("");
  const [consent, setConsent] = useState(false), [busy, setBusy] = useState(false), [notice, setNotice] = useState("Opening your device task…"), [saved, setSaved] = useState(false);
  const pending = useRef<{ requestId: string; fingerprint: string } | null>(null);
  const load = useCallback(async (key: string) => {
    setBusy(true); setSaved(false);
    try { const data = await connectedApi({ operation: "read", token: key }); setTask(data); setState(data.progress?.state ?? "agent-help"); setDeviceId(data.progress?.deviceId ?? ""); setConsent(false); pending.current = null; setNotice(data.progress ? "Your last update is saved in CoverageFit. You can review or change it below." : "Nothing is preselected for purchase. Your insurance decision and appointment remain in CoverageFit."); }
    catch (error) { setNotice(error instanceof Error ? error.message : "Connection unavailable."); }
    finally { setBusy(false); }
  }, []);
  useEffect(() => { const key = new URLSearchParams(window.location.hash.slice(1)).get("h") ?? ""; const frame = requestAnimationFrame(() => { setToken(key); if (/^[A-Za-z0-9_-]{43}$/.test(key)) void load(key); else setNotice("Open this page from the device task in your CoverageFit insurance review. You can browse independent guidance below."); }); return () => cancelAnimationFrame(frame); }, [load]); // Initial opaque capability only; never the insurance review token.
  function changed() { setSaved(false); setConsent(false); pending.current = null; }
  async function save() {
    if (!task || !consent || busy) return;
    const update = { expectedVersion: task.version, state, deviceId: state === "considering" ? deviceId : "", consent: true };
    const fingerprint = JSON.stringify(update); if (pending.current?.fingerprint !== fingerprint) pending.current = { requestId: crypto.randomUUID(), fingerprint };
    setBusy(true); setNotice("Saving your update to CoverageFit…");
    try { const result = await connectedApi({ operation: "save", token, ...update, requestId: pending.current.requestId }); setTask({ ...task, version: result.version, progress: result.progress }); setSaved(true); setConsent(false); pending.current = null; setNotice("Saved to your insurance review. Your agent can see this update. Product suitability, professional review and insurer acceptance are not confirmed by this action."); }
    catch (error) { setNotice(error instanceof Error ? error.message : "No save is confirmed. Retry this update."); }
    finally { setBusy(false); }
  }
  return <section className="home-decision connected-device-task" aria-labelledby="connected-title">
    <header className="hd-heading"><div><p className="eyebrow">Connected to your CoverageFit review</p><h1 id="connected-title">One clearer next step for your home.</h1><p>Review water-shutoff options or tell your agent what help you need.</p></div>{returnOrigin && token ? <a className="button-subtle" href={`${returnOrigin}/review/#deviceReturn=${token}`}>Return to my insurance review</a> : null}</header>
    <p className="hd-notice" role="status" aria-live="polite">{notice}</p>
    {task ? <>
      <aside className="hd-context"><strong>{task.policy.carrier} · {task.policy.product}</strong><h2>{taskKinds[task.task.kind]}</h2>{task.task.dueDate ? <p>Documented due date: {task.task.dueDate}</p> : null}<p>This is an agent-supplied task for the linked policy, not a SmartDevices or carrier determination. Read the exact next-step instruction in your insurance review. SmartDevices is independent.</p></aside>
      <div className="hd-workbench"><div className="hd-decision-card"><p className="eyebrow">Understand the capability</p><h2>Automatic water shutoff</h2><p>Compare main-line monitoring with automatic valve control. A point sensor alone does not shut off the main water supply.</p><p>Confirm plumbing fit, installation permission, power, network requirements and a separate installation quote with a qualified professional.</p><p>Equipment and subscriptions are separate from your insurance premium. No option shown here establishes policy eligibility or a discount.</p></div><figure className="hd-house"><Image unoptimized src="/assets/home-protection-hero.png" alt="Illustrative cutaway home, not an assessment of your property" width="1664" height="936" style={{ width: "100%", height: "auto" }} /><figcaption>Illustrative home · your property has not been assessed</figcaption></figure></div>
      <section className="hd-options" aria-labelledby="connected-options"><h2 id="connected-options">Compare the practical details</h2><div className="hd-option-grid" data-count={options.length}>{options.map(device => <article className="hd-option" key={device.id}><p className="eyebrow">{device.manufacturer}</p><h3>{device.model}</h3><p>{device.solution}</p><p className="hd-record-date">Record checked {device.lastReviewed}</p><p className="hd-availability">{device.availability === "unavailable" ? "Unavailable when last checked. Do not assume it can be purchased now." : "Confirm current stock and pricing before purchasing."}</p><dl><div><dt>Equipment · dated context</dt><dd>{device.priceBand}</dd></div><div><dt>Installation · separate cost</dt><dd>{device.installation}. Obtain a site-specific quote.</dd></div><div><dt>Subscription</dt><dd>{device.subscription}</dd></div></dl><details><summary>Compatibility, limitations and sources</summary><p>{device.connectivity}</p><ul>{device.limitations.map(item => <li key={item}>{item}</li>)}</ul><p>Review current privacy terms, account access and household consent. Commercial status: {device.commercialStatus}.</p><ul>{device.sources.map(source => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer noopener">{source.title}</a></li>)}</ul></details><Link className="hd-text-link" href={`/devices/${device.slug}`} target="_blank" rel="noopener noreferrer">Full device record (new tab)</Link></article>)}</div>{!options.length ? <p>No current reviewed match is available. You can still ask your agent for help; we won’t substitute an unsupported product.</p> : null}</section>
      <section className="hd-next" aria-labelledby="connected-update"><h2 id="connected-update">What should your agent know?</h2><label className="hd-field">Your next step<select disabled={busy} value={state} onChange={event => { changed(); setState(event.target.value as DeviceTaskState); }}>{Object.entries(deviceTaskStates).map(([id,label]) => <option key={id} value={id}>{label}</option>)}</select></label>{state === "considering" ? <label className="hd-field">Device you are considering<select disabled={busy} value={deviceId} onChange={event => { changed(); setDeviceId(event.target.value); }}><option value="">Choose an option — nothing preselected</option>{options.map(device => <option key={device.id} value={device.id}>{device.manufacturer} {device.model}</option>)}</select></label> : null}<p>Your update shares only the selected status and, if applicable, device identifier. No order, installation appointment or insurance change is made.</p><label className="hd-consent"><input type="checkbox" disabled={busy} checked={consent} onChange={event => setConsent(event.target.checked)} /> Save this update to my linked CoverageFit review for my agent to see.</label><div className="hd-primary-row"><button className="button-primary" disabled={busy || !consent || (state === "considering" && !deviceId)} onClick={save}>{busy ? "Please wait…" : saved ? "Update saved" : "Save update to my insurance review"}</button><button className="button-subtle" disabled={busy} onClick={() => load(token)}>Reload saved update</button></div><p>Customer-reported installation is not installation evidence or professional verification. No document upload is available here. Your request to proceed and existing appointment are preserved in CoverageFit.</p></section>
    </> : token ? <button className="button-subtle" disabled={busy} onClick={() => load(token)}>Retry connection</button> : null}
    <footer className="hd-footer"><Link href="/protect/home">Browse independent Home guidance</Link><p>CoverageFit owns your insurance review. SmartDevices provides independent device information. Buying or selecting a device does not start insurance coverage.</p></footer>
  </section>;
}
