import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { buildCarrierContext } from "../app/lib/carrier-scan";
import { canonicalCarrierHref } from "../app/lib/carrier-route";
import { evaluateCarrierGuidance, publishedCarriers, type CarrierGuidanceDataset, type CarrierRecord, type CarrierRule, type DeviceClass, type EvidenceSource } from "../app/lib/carrier";
import { createCarrierPlan } from "../app/lib/plan";
import { carrierTemplateState, type CarrierPlanTemplate } from "../app/lib/pro-templates";
import { validateCarrierHandoffContext } from "../app/lib/integrations";

const carrier: CarrierRecord = { id: "test-horizon", slug: "test-horizon", name: "Horizon Test Carrier", publicationStatus: "published", supportedJurisdictions: ["OR"], canonicalPath: "/test-horizon", disclosure: "Test-only fixture." };
const source: EvidenceSource = { id: "test-horizon-source-v1", version: 1, owner: "Horizon Test Carrier", domain: "example.test", title: "Test source", url: "https://example.test/source", jurisdictions: ["OR"], checkedDate: "2026-08-26", reviewDueDate: "2026-09-25", status: "active", visibility: "public", limitations: ["Test only."] };
const rule: CarrierRule = { id: "test-horizon-security-v1", version: 1, programId: "test-program", carrierId: carrier.id, jurisdiction: "OR", line: "homeowners", policyScope: "unknown", classification: "potential-discount-category", capabilityClassIds: ["professionally-monitored-fire-security"], sourceIds: [source.id], checkedDate: "2026-08-26", reviewDueDate: "2026-09-25", reviewer: "test", reviewStatus: "reviewed", status: "active", visibility: "public", limitations: ["Test only."] };
const classes: DeviceClass[] = [{ id: "professionally-monitored-fire-security", label: "Monitored protection", description: "Test", safetyBoundary: "Test only" }];
const dataset: CarrierGuidanceDataset = { carriers: [carrier], rules: [rule], fits: [] };

test("test-only carrier flows through directory, route, scan, labels, and plan contracts", () => { assert.equal(publishedCarriers([carrier])[0].id, carrier.id); assert.equal(canonicalCarrierHref({ intent: "discounts", category: "security" }, carrier.canonicalPath), "/test-horizon?intent=discounts&category=security"); const context = buildCarrierContext("discounts", "security", [{ questionId: "jurisdiction", optionId: "OR" }, { questionId: "security-capability", optionId: "professional" }], carrier.id); assert.equal(context.carrierId, carrier.id); assert.equal(context.jurisdiction, "OR"); const guidance = evaluateCarrierGuidance(context, "2026-08-26", dataset); assert.match(guidance.map((item) => item.label).join(" "), /Horizon Test Carrier/); assert.equal(createCarrierPlan(context, []).carrierProvenance.carrierId, carrier.id); });
test("test-only carrier flows through Pro template and handoff contracts", () => { const template: CarrierPlanTemplate = { id: "fixture-security", name: "Fixture security", carrierId: carrier.id, jurisdiction: "OR", category: "security", intent: "requirement", capabilityIds: rule.capabilityClassIds, requiredRuleIds: [rule.id], confirmation: "Test confirmation." }; assert.equal(carrierTemplateState(template, [rule]), "available"); const result = validateCarrierHandoffContext({ carrierId: carrier.id, jurisdiction: "OR", entryIntent: "discounts", capabilityIds: rule.capabilityClassIds, ruleSources: [{ ruleId: rule.id, ruleVersion: 1, sourceId: source.id, sourceVersion: 1 }], unknownIds: [] }, { getCarrier: (id) => id === carrier.id ? carrier : undefined, rules: [rule], sources: [source], classes }); assert.equal(result.carrierId, carrier.id); });
test("generic carrier components contain no carrier-name branch", () => { for (const relative of ["CarrierIntentSelector.tsx", "CarrierProtectionMap.tsx", "CarrierDeviceOptions.tsx", "CarrierScan.tsx", "IndependentRecommendations.tsx", "SafetyPlanClient.tsx", "ProWorkspace.tsx"]) { const sourceText = fs.readFileSync(new URL(`../app/components/${relative}`, import.meta.url), "utf8"); assert.doesNotMatch(sourceText, /(?:if|switch)[^\n]*(?:Farmers|farmers)|carrierId\s*===?\s*[\"']farmers/i, relative); } });
