import test from "node:test";
import assert from "node:assert/strict";
import { validateHandoff } from "../app/lib/integrations";

const base = { handoffId: "hof_v3carrier", sourceSystem: "coveragefit", destinationSystem: "smartdevices-pro", issuedAt: new Date(Date.now() - 1_000).toISOString(), expiresAt: new Date(Date.now() + 60_000).toISOString(), consent: { purpose: "protection-plan", capturedAt: new Date().toISOString(), policyVersion: "carrier-handoff-v3" } };
const carrier = { carrierId: "farmers", jurisdiction: "CA", entryIntent: "requirement", capabilityIds: ["automatic-main-water-shutoff"], ruleSources: [{ ruleId: "farmers-ca-water-category-v1", ruleVersion: 1, sourceId: "farmers-home-discounts-2026-08-26", sourceVersion: 1 }], assertionSource: "consumer-stated", unknownIds: ["policy-scope"] };
test("v3 transfers bounded carrier context without repeat questions", () => { const handoff = validateHandoff({ ...base, schemaVersion: 3, context: { domain: "home", concernIds: ["water"], deviceIds: ["moen-flo-shutoff"], clientIntent: "verify-carrier", carrier } }); assert.equal(handoff.schemaVersion, 3); assert.ok(handoff.schemaVersion === 3 && handoff.context.carrier?.capabilityIds.includes("automatic-main-water-shutoff")); });
test("v1 and v2 remain compatible", () => { assert.equal(validateHandoff({ ...base, handoffId: "hof_legacy1", schemaVersion: 1, context: { domain: "home", concernIds: ["water"] } }).schemaVersion, 1); assert.equal(validateHandoff({ ...base, handoffId: "hof_legacy2", schemaVersion: 2, context: { domain: "home", concernIds: ["water"], clientIntent: "researching" } }).schemaVersion, 2); });
test("invalid carrier, jurisdiction, capability, rule, or version is rejected", () => { for (const changed of [{ carrierId: "unknown" }, { jurisdiction: "NV" }, { capabilityIds: ["fake-class"] }, { ruleSources: [{ ...carrier.ruleSources[0], ruleVersion: 999 }] }, { ruleSources: [{ ...carrier.ruleSources[0], sourceVersion: 999 }] }]) assert.throws(() => validateHandoff({ ...base, schemaVersion: 3, context: { domain: "home", carrier: { ...carrier, ...changed } } }), /INVALID_/); });
test("nested sensitive fields and unversioned carrier context are rejected", () => { assert.throws(() => validateHandoff({ ...base, schemaVersion: 3, context: { domain: "home", carrier: { ...carrier, policyNumber: "secret" } } }), /PROHIBITED/); assert.throws(() => validateHandoff({ ...base, schemaVersion: 2, context: { domain: "home", carrier } }), /V3_CONTEXT/); });
test("expired and consentless envelopes remain rejected", () => { assert.throws(() => validateHandoff({ ...base, expiresAt: "2020-01-01T00:00:00Z", schemaVersion: 3, context: { carrier } }), /EXPIRED/); assert.throws(() => validateHandoff({ ...base, consent: undefined, schemaVersion: 3, context: { carrier } }), /CONSENT/); });
