import assert from "node:assert/strict";
import test from "node:test";
import { DatabaseSync } from "node:sqlite";
import { readFileSync, mkdtempSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { projectStore } from "../app/lib/builder-store";
import { builderRequest } from "../app/lib/builder-http";
import { hostingBoundary, PRIVATE_HEADERS } from "../app/lib/hosting-policy";
import { sitesPrincipal } from "../app/lib/sites-principal";
import { createDeviceProject, selectProjectArchitecture } from "../app/lib/builder-engine";
import { devices } from "../app/lib/data";
import type { ProjectDatabase, ProjectStatement } from "../db/project-database";
const A="sites:synthetic-user-a", B="sites:synthetic-user-b";
const origin="https://isolated.example";
function project(){return createDeviceProject("SYNTHETIC TEST: Monitor the temperature inside a freezer",{environment:"indoor",power:"usb",connectivity:"wifi",deploymentIntent:"auto",quantity:1,goal:"functional-prototype",budget:"30-75"},devices);}
function database(path=":memory:",migrate=true){
 const sqlite=new DatabaseSync(path);sqlite.exec("PRAGMA foreign_keys=ON");
 if(migrate){const journal=JSON.parse(readFileSync("drizzle/meta/_journal.json","utf8"));for(const entry of journal.entries)sqlite.exec(readFileSync(`drizzle/${entry.tag}.sql`,"utf8"));}
 class Statement implements ProjectStatement { values:(string|number|null)[]=[];constructor(public sql:string){} bind(...values:(string|number|null)[]){this.values=values;return this;}async first<T>(){return (sqlite.prepare(this.sql).get(...this.values)??null) as T|null;}async all<T>(){return {results:sqlite.prepare(this.sql).all(...this.values) as T[]};}}
 const db:ProjectDatabase={prepare:(sql)=>new Statement(sql),async batch(statements){sqlite.exec("BEGIN IMMEDIATE");try{const results=statements.map(s=>{const x=s as Statement;return {meta:{changes:Number(sqlite.prepare(x.sql).run(...x.values).changes)}};});sqlite.exec("COMMIT");return results;}catch(error){sqlite.exec("ROLLBACK");throw error;}}};
 return {sqlite,store:projectStore(db)};
}
const request=(method:string,body?:unknown,id?:string)=>new Request(origin+"/api/builder/projects"+(id?"/"+id:""),{method,headers:{Origin:origin,"Content-Type":"application/json"},...(body?{body:JSON.stringify(body)}:{})});

test("stable principal uses Sites ID and never accepts email alone",()=>{assert.equal(sitesPrincipal(new Headers({"oai-authenticated-user-email":"a@example.test"})),null);assert.equal(sitesPrincipal(new Headers({"oai-authenticated-user-id":"subject-a"})),"sites:subject-a");});
test("SQLite persistence survives closing/reopening the process connection",async()=>{const dir=mkdtempSync(join(tmpdir(),"sd-persist-"));try{const path=join(dir,"test.sqlite");const first=database(path);const p=await first.store.save(project(),A);first.sqlite.close();const second=database(path,false);assert.deepEqual(await second.store.read(p.id,A),p);assert.equal((await second.store.list(A))[0].id,p.id);second.sqlite.close();}finally{rmSync(dir,{recursive:true,force:true});}});
test("A/B isolation: list read update create-collision export and preserved A access",async()=>{const {store,sqlite}=database();const p=await store.save(project(),A);assert.deepEqual(await store.list(B),[]);assert.equal(await store.read(p.id,B),null);await assert.rejects(store.save({...p,revision:2},B,true),/NOT_FOUND/);await assert.rejects(store.save(p,B),/NOT_FOUND/);await assert.rejects(store.exportProject(p.id,B),/NOT_FOUND/);assert.deepEqual(await store.read(p.id,A),p);sqlite.close();});
test("immutable revisions reject changed same-revision save; retry returns actual persisted timestamp",async()=>{const {store,sqlite}=database();const p=await store.save(project(),A);assert.deepEqual(await store.save({...p,updatedAt:"client-time"},A),p);await assert.rejects(store.save({...p,title:"Unpersisted change"},A),/REVISION_CONFLICT/);assert.equal((await store.list(A))[0].title,p.title);const next=await store.save(selectProjectArchitecture(p,"production-minded"),A,true);assert.equal((await store.read(p.id,A))?.revision,next.revision);await assert.rejects(store.save(p,A),/REVISION_CONFLICT/);sqlite.close();});
test("batch failure rolls back parent insertion; no fake success",async()=>{const {store,sqlite}=database();sqlite.exec("CREATE TRIGGER fail_revision BEFORE INSERT ON builder_revisions BEGIN SELECT RAISE(ABORT,'simulated write failure'); END;");await assert.rejects(store.save(project(),A),/simulated write failure/);assert.equal((await store.list(A)).length,0);sqlite.close();});
test("export and restore into a clean database retains all revision content with a new ID and owner",async()=>{const first=database(),second=database();const p=await first.store.save(project(),A);const next=await first.store.save(selectProjectArchitecture(p,"production-minded"),A,true);const backup=await first.store.exportProject(p.id,A);assert.equal(backup.revisions.length,2);assert.ok(!JSON.stringify(backup).includes(A));const restored=await second.store.restoreProject(backup,B);assert.notEqual(restored.id,p.id);assert.equal(restored.revision,next.revision);assert.equal(restored.idea,next.idea);assert.equal((await second.store.exportProject(restored.id,B)).revisions.length,2);assert.equal(await second.store.read(restored.id,A),null);assert.equal(await second.store.read(p.id,B),null);first.sqlite.close();second.sqlite.close();});
test("HTTP boundary enforces signed-out/IDOR/invalid-ID/update/delete/cache contracts",async()=>{const {store,sqlite}=database();const p=await store.save(project(),A);const provide=async()=>store;assert.equal((await builderRequest(request("GET"),null,provide)).status,401);assert.equal((await builderRequest(request("GET",undefined,p.id),B,provide,p.id)).status,404);assert.equal((await builderRequest(request("PUT",{...p,revision:2},p.id),B,provide,p.id)).status,404);assert.equal((await builderRequest(request("GET"),A,provide,"../../bad")).status,404);assert.equal((await builderRequest(request("DELETE",undefined,p.id),B,provide,p.id)).status,405);const read=await builderRequest(request("GET",undefined,p.id),A,provide,p.id);assert.equal(read.status,200);assert.equal(read.headers.get("cache-control"),PRIVATE_HEADERS["Cache-Control"]);assert.equal((await read.json()).project.id,p.id);sqlite.close();});
test("HTTP boundary returns 503 on unavailable/mismatched database, never saved",async()=>{const unavailable=async()=>{throw new Error("SQLITE schema missing secret detail");};for(const method of ["GET","POST"]){const response=await builderRequest(request(method,method==="POST"?project():undefined),A,unavailable);assert.equal(response.status,503);assert.ok(!(await response.text()).includes("secret detail"));}});
test("HTTP boundary rejects cross-site save, oversized bodies, malformed JSON and unknown updates",async()=>{const {store,sqlite}=database();const provide=async()=>store;const cross=new Request(origin+"/api/builder/projects",{method:"POST",headers:{origin:"https://evil.test"},body:"{}"});assert.equal((await builderRequest(cross,A,provide)).status,403);assert.equal((await builderRequest(request("POST",{padding:"x".repeat(256001)}),A,provide)).status,413);const bad=new Request(origin+"/api/builder/projects",{method:"POST",headers:{Origin:origin,"Content-Type":"application/json"},body:"[broken"});assert.equal((await builderRequest(bad,A,provide)).status,400);const p=project();assert.equal((await builderRequest(request("PUT",p,p.id),A,provide,p.id)).status,404);sqlite.close();});
test("deployment boundary blocks every unrelated API mutation and all external-operation endpoints",()=>{for(const path of ["/api/builder/execute","/api/builder/research","/api/builder/source","/api/devices/register","/api/integrations/handoff","/api/market/conversion/provider","/api/internal/evidence-refresh","/api/operate","/api/payments","/_vinext/image"]){for(const method of ["GET","POST","PUT","DELETE"]){assert.equal(hostingBoundary(new Request(origin+path,{method}))?.status,403,path);}}assert.equal(hostingBoundary(request("POST",project())),null);assert.equal(hostingBoundary(new Request(origin+"/build",{method:"POST"}))?.status,403);});
test("synthetic CRUD journey through HTTP handlers: create list fresh read update and read again",async()=>{const {store,sqlite}=database();const provide=async()=>store;const created=await builderRequest(request("POST",project()),A,provide);assert.equal(created.status,201);const p=(await created.json()).project;const listed=await builderRequest(request("GET"),A,provide);assert.equal((await listed.json()).projects[0].id,p.id);const reread=await builderRequest(request("GET",undefined,p.id),A,provide,p.id);const next=selectProjectArchitecture((await reread.json()).project,"production-minded");assert.equal((await builderRequest(request("PUT",next,p.id),A,provide,p.id)).status,200);assert.equal((await store.read(p.id,A))?.revision,next.revision);sqlite.close();});
